<?php

/*******************************************/
$DevMode = false;

if(!isset($_GET['software'])){
    echo "Error, variable software invalida.";
    die;
}

/* github */
$GithubUsernameToken = "GithubUsernameToken";
$GithubUsername = "GithubUsername";

$software = $_GET['software']; // use a Get param to specify the repository

// set the github correspondent project
if($software=="XXX"){

    $GithubRepository = "XXX";

}else if($software=="YYY"){

    $GithubRepository = "YYY";

}else{
    echo "Error, variable software invalid.";
    die;

}


/*******************************************/
session_start();



if(!isset($_POST['title']) && !isset($_POST['issue']) && !isset($_POST['submit'])){
    // start session var.
    $_SESSION["IsRecaptchaOK"] = false;
}

require __DIR__ . '/appengine-https.php';

// Initiate the autoloader. The file should be generated by Composer.
// You will provide your own autoloader or require the files directly if you did
// not install via Composer.
require_once __DIR__ . '/Vendor/Recaptcha/autoload.php';

// Register API keys at https://www.google.com/recaptcha/admin
$siteKey = '';
$secret = '';

// update config.php it with your keys to run the examples or copy to
// config.development.php and set dev/private keys and set $DevMode = true.
if(!$DevMode){
    if ($siteKey == '' && is_readable(__DIR__ . '/config.php')) {
        $config = include __DIR__ . '/config.php';
        $siteKey = $config['v3']['site'];
        $secret = $config['v3']['secret'];
    }
}else{
    $config = include __DIR__ . '/config.development.php';
    $siteKey = $config['v3']['site'];
    $secret = $config['v3']['secret'];
}

// reCAPTCHA supports 40+ languages listed here: https://developers.google.com/recaptcha/docs/language
$lang = 'en';

include_once("Include/inc_DB.php");
include_once("Include/inc_Github.php");

$showMsg = "";
if(isset($_POST['title']) && isset($_POST['issue']) && isset($_POST['submit'])){

    if($_SESSION["IsRecaptchaOK"] == true ){

        $pdo = (new SQLiteConnection())->connect();
        $sqlite = new SQLiteInsert($pdo);

        $software = isset($_GET['software']) ? $_GET['software'] : "?";

        $sqlite->insertTask($_POST['title'], $_POST['issue'], $software );

        SendToGithub();

        $showMsg ='<div class="alert alert-success">Gracias, reporte enviado.</div>';
    } else{
        $showMsg ='<div class="alert alert-danger">Disculpenos, Error enviando el reporte.</div>';

    }
}


?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="Javier Cañon" />
    <link rel="icon" href="favicon.ico" />

    <title>Issue Reporting</title>

    <!-- Bootstrap core CSS -->
    <link crossorigin='anonymous' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' rel='stylesheet' />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous" />

    <!-- Custom styles for this template -->
    <link href="Css/StyleSheet.css" rel="stylesheet" />
</head>

<body>
    <?php
    if ($siteKey === '' || $secret === ''):
    ?>
    <h2>Add your keys</h2>
    <p>
        If you do not have keys already then visit
        <kbd>
            <a href="https://www.google.com/recaptcha/admin">https://www.google.com/recaptcha/admin</a>
        </kbd> to generate them. Edit this file and set the respective keys in
        <kbd>$siteKey</kbd> and
        <kbd>$secret</kbd>. Reload the page after this.
    </p>
    <?php
    else:
        // Add the g-recaptcha tag to the form you want to include the reCAPTCHA element
    ?>
    <form id="formReport" action="index.php?<?php echo $_SERVER['QUERY_STRING'] ?>" class="form-reporting" method="post" enctype="multipart/form-data">
        <div class="text-center mb-4">

            <h1 class="h3 mb-3 font-weight-normal">
                <i class="fas fa-bug fa-2x"></i> Reportar una Incidencia
            </h1>
            <p>
                Por favor utilice el siguiente formulario para reportar una incidencia o bug,
                trate de explicar los detalles para poder reproducir la falla,
                copie links a fotos o videos
                (Google Drive, Google Photos, Microsoft Onedrive, Dropbox, Wetransfer, etc.).
            </p>
        </div>

        <?php echo $showMsg; ?>

        <div class="form-label-group" id="honeybotpot">
            <input type="email" class="form-control" name="email" id="email" value="" placeholder="E-mail" />
        </div>

        <div class="form-label-group">
            <label for="title">Titulo u Asunto</label>
            <input type="text" id="title" name="title" class="form-control" placeholder="Issue Title" required autofocus
                value="<?php if(isset($_GET['title'])) { echo $_GET['title']  ;} ?>" />
        </div>

        <div class="form-label-group">
            <label for="issue">Detalles Incidencia</label>
            <textarea id="issue" name="issue" class="form-control" placeholder="Issue Text" maxlength="4000"
                rows="10" required>
                <?php if(isset($_GET['issue'])) { echo $_GET['issue'] ;}?>
            </textarea>
        </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit" name="submit">
            <i class="fa fa-share-square" aria-hidden="true"></i> Enviar
        </button>

        <div class="alert alert-danger" id="sendMsgError" style="display:none;">
            <strong>Error</strong> No se pudo enviar el reporte.
        </div>

        <div class="alert alert-success" id="sendMsgOK" style="display:none;">
            <strong>Gracias,</strong> Reporte enviado.
        </div>
        <?php if($DevMode){ ?>
        <div id="response" class="alert alert-danger"></div><?php } ?>
        <p class="mt-5 mb-3 text-muted text-center">&copy; 2019</p>
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://www.google.com/recaptcha/api.js?render=<?php echo $siteKey; ?>"></script>


    <script>

        $.fn.captcha = function (param) {

            var params = $.extend({
                idCaptchaText: 'captchaText',
                idCaptchaInput: 'captchaInput',
                class: ''
            }, param);

            var submit = $(this).find('button[type=submit]');
            submit.attr('disabled', 'disabled');
            submit.addClass('btn-secondary disabled');

            $('<div class="form-label-group"><label id="' + params.idCaptchaText + '"></label>' + '<input class="form-control" placeholder="Anti SPAM" id="' + params.idCaptchaInput + '" aria-label="Captcha Input" type="text" required="required" /></div>').insertBefore(submit);

            var label = this.find('#' + params.idCaptchaText);
            var input = this.find('#' + params.idCaptchaInput);

            var rndmNr1 = Math.floor(Math.random() * 10),
                rndmNr2 = Math.floor(Math.random() * 10),
                totalNr = rndmNr1 + rndmNr2;

            $(label).text('Cuanto es? ' + rndmNr1 + ' + ' + rndmNr2 + ' =');

            $(input).keyup(function () {
                if ($(this).val() == totalNr)
                    submit.removeAttr('disabled').removeClass('btn-secondary disabled').addClass('btn-primary');
                else
                    submit.attr('disabled', 'disabled');
            });

            return this;
        }


        $(document).ready(function () {
            $('#formReport').captcha();
            $('#honeybotpot').hide();
        });

        var frm = $('#formReport');

        frm.submit(function (e) {

            //e.preventDefault();

            // check honeypot
            if (document.getElementById("email").value) {
                console.log('An error occurred.');
                return false;
            }

            if (!reCaptchaSuccess) { $('#sendMsgError').show(); return false; }
            if (reCaptchaScore < 0.4) { $('#sendMsgError').show(); return false; }

            return true;
        });

    </script>

    <script>

     var reCaptchaScore = 0;
     var reCaptchaSuccess = false;

     grecaptcha.ready(function() {

        grecaptcha.execute('<?php echo $siteKey; ?>', {action: 'homepage'}).then(function(token) {
            fetch('/recaptcha-v3-verify.php?token='+token).then(function(response) {
                response.json().then(function(data) {

                   var resp = JSON.parse(JSON.stringify(data));
                   reCaptchaScore = resp.score;
                   reCaptchaSuccess = resp.success;
                   <?php if($DevMode) { ?> document.querySelector('#response').innerHTML = JSON.stringify(data, null, 2); <?php } ?>
                });
            });
        });
    });
    </script>
    <?php
    endif;?>
</body>
</html>
